package UiStart;






import database.Connector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author pawel
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * @return the resultTable
     */
    public static javax.swing.JTable getResultTable() {
        return resultTable;
    }

    /**
     * @param aResultTable the resultTable to set
     */
    public static void setResultTable(javax.swing.JTable aResultTable) {
        resultTable = aResultTable;
    }
    
    public static void setTableModel(DefaultTableModel model) {
        tabmod = model;
    }

    public static DefaultTableModel getTableModel(){
        
    return tabmod;
    }
    /**
     * Creates new form MainWindow
     */
    public static DefaultTableModel tabmod;

    public MainWindow(DefaultTableModel model) {

        this.tabmod = model;
        this.setTitle("MAGAZYN CZĘŚCI");
        this.setResizable(true);

        int rows = tabmod.getRowCount();
        
        if (rows < 1) {
            
           JOptionPane.showMessageDialog(this, "Oczekuję na połączenie z bazą danych.");
        } 

        resultTable.setModel(tabmod);
        initComponents();
    }
        
    public MainWindow() {

        
        this.setTitle("MAGAZYN CZĘŚCI");
        this.setResizable(true);
         initComponents();
        int rows = tabmod.getRowCount();
         
        if (rows < 1) {
            
           JOptionPane.showMessageDialog(this, "Oczekuję na połączenie z bazą danych.");
        } 

        resultTable.setModel(tabmod);
        this.repaint();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablePanel = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        windowText = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        searchButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tablePanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        tablePanel.setAutoscrolls(true);
        tablePanel.setFocusable(false);
        tablePanel.setHorizontalScrollBar(null);
        tablePanel.setMaximumSize(getSize());
        tablePanel.setNextFocusableComponent(resultTable);
        tablePanel.setViewportView(resultTable);

        resultTable.setModel(tabmod);
        tablePanel.setViewportView(resultTable);

        windowText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        windowText.setText("Stan Magazynowy Części");

        addButton.setText("DODAJ");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        searchButton1.setText("SZUKAJ");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(windowText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(windowText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(searchButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        AddWindow adder = new AddWindow();
        adder.setVisible(true);
        this.dispose();
        

    }//GEN-LAST:event_addButtonActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        // TODO add your handling code here:

        SearchWindow sWin = new SearchWindow();
        sWin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {

            
            String cmd = "powershell.exe Start-Process -FilePath STOP.bat -verb RunAs";
            Runtime rt = Runtime.getRuntime();
            Process proc = rt.exec(cmd);

            // any error message?
            Init.StreamGobbler errorGobbler = new Init.StreamGobbler(proc.getErrorStream(), "ERR");

            // any output?
            Init.StreamGobbler outputGobbler = new Init.StreamGobbler(proc.getInputStream(), "OUT");

            // kick them off
            errorGobbler.start();
            outputGobbler.start();

            // any error???
            int exitVal = proc.waitFor();
            System.out.println("ExitValue: " + exitVal);

        } catch (Throwable t) {

            t.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new MainWindow().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JTable resultTable;
    private javax.swing.JButton searchButton1;
    private static javax.swing.JScrollPane tablePanel;
    private javax.swing.JLabel windowText;
    // End of variables declaration//GEN-END:variables
}
